### ISSUE TITLE
Float constraint for longitude and latitude runs into problems with degree sign and N/S E/W

### ISSUE THREAD

**Issue by GregLyonJIFSAN** [kaiiam/mifc#14]
It looks like the PTFI metadata values for longitude and latitude are formatted in a way that is not compatible with the range constraint in mifc.yaml. The Foundation Foods QC platform logged the following error when trying to convert the TSV sample data to JSON using the linkml-convert utility:

`ValueError: could not convert string to float: '37.2296° N'
`

Maybe we could make this field a string and validate it using a regex? Alternatively, it could be a tuple with a float component for degrees and a character for N/S/E/W. I don't know if we would expect values expressed in degrees, minutes, seconds, but that might be another possibility to keep in mind.

These are the relevant fields in mifc.yaml:

```
  food_acquisition_latitude: #TODO add numeric range constraint
    description: A float representing the latitude of the place from which the primary_food_type was acquired.
    range: float
    exact_mappings:
      - PTFI:Collection_Latitude
  food_acquisition_longitude: #TODO add numeric range constraint
    description: A float representing the longitude of the place from which the primary_food_type was acquired.
    range: float
    exact_mappings:
      - PTFI:Collection_Longitude
```
